### ISSUE TITLE
[close]您好，请问你是南校还是北校呢？

### ISSUE THREAD

**Issue by ghost** [scutclient/pyscutclient_drcom#1]

**Comment by 7forz** [comment]
我已经毕业了。这个程序不发udp包，应该是不能稳定认证的（不知道多久断一次）。更多信息请关注华工路由器群~

**Comment by ghost** [comment]
我网上找了个不知道哪个学校的easyDrcom，能认证成功，不过过阵子就断网。求华工路由器群号？找不到啊

**Comment by 7forz** [comment]
现在闹得沸沸扬扬，群号还不好找？百度华工路由器群即可找到审核群。另外我这个python文件里面就有群号..

**Comment by 7forz** [comment]
udp包不对的话，只过了802.1x认证，还是会断的呀
