### ISSUE TITLE
udp auth

### ISSUE THREAD

**Issue by iseekwonderful** [scutclient/pyscutclient_drcom#2]
在keep-alive-pkt1(`def send_udp_38byte_alive()`) 函数中的
`p_udp_38byte_alive.load = '\xff' + crc_8byte_for_244byte_info + p_md5.load[5:17] + 3 * '\x00' + \
                              '\x44\x72\x63\x6f' + DST_IP_HEX + '\x2e\x63' + MY_IP_HEX + '\x41\x68' + '\x00\x00'
`
其中`\x2e\x63`和`\x41\x68`好像不是固定值，而是一个序列值。
学校提供的客户端和scutdrcom里都是每次认证增加，但是每次keep-alive不变的值，能否告知这4bytes的计算方法。 

另外: `update_udp_misc1`中的：
`p_udp_misc1.load = '\x07' + chr(drcom_pkt_id) + '\x28\x00\x0b\x01\x0f\x27' + misc_random_4bytes + 28 * '\x00'
`
`'\x28\x00\x0b\x01\x0f\x27'`  改成 `'\x28\x00\x0b\x01\xdc\x02'` 才能收到misc2

**Comment by 7forz** [comment]
’\x2e\x63‘和’\x41\x68‘是会变，但是不知道怎么变，可能是我看的抓包比较少（只看过hwy_linux.pcapng）
'\x28\x00\x0b\x01\x0f\x27'也是看hwy_linux.pcapng写的。

scutclient的主要开发者都毕业了，没有现场测试的环境。
我写的这个也没有人反馈过能不能用o(_￣▽￣_)o 

我这代码写得烂。未来你们南校的同学要多给力啊。

**Comment by iseekwonderful** [comment]
我说的`4bytes`就是’\x2e\x63‘和’\x41\x68‘, - -
我刚刚进到了测试群,看了C的实现, 已经搞定了
你是群里的7F吗，如果可以公开的话，我提交一个commit上来

**Comment by 7forz** [comment]
好啊好啊
